#!/usr/bin/env bash

# This script requires the following executables:
# - /usr/local/bin/jq
# - /usr/bin/curl
# - /usr/bin/xargs
# - /usr/bin/bc
# - /usr/bin/awk

add_arrows() {
  string=$(echo $1 | sed -e 's/^\([0-9]\)/▲ \1/g')
  string=$(echo $string | sed -e 's/^-/▼ /g')
  echo $string
}

fetch_data() {
  echo $(/usr/bin/curl -s -XGET "https://api.coinmarketcap.com/v1/ticker/$1/?convert=usd")
}

eth=$(fetch_data 'ethereum')
eth_to_usd=$(echo $eth | /usr/local/bin/jq ".[0].price_usd" | /usr/bin/xargs printf "%.*f\n" 2)
eth_24h=$(echo $eth | /usr/local/bin/jq ".[0].percent_change_24h" | /usr/bin/xargs printf "%.*f\n" 2)
eth_1h=$(echo $eth | /usr/local/bin/jq ".[0].percent_change_1h" | /usr/bin/xargs printf "%.*f\n" 2)

btc=$(fetch_data 'bitcoin')
btc_to_usd=$(echo $btc | /usr/local/bin/jq ".[0].price_usd" | /usr/bin/xargs printf "%.*f\n" 2)
btc_24h=$(echo $btc | /usr/local/bin/jq ".[0].percent_change_24h" | /usr/bin/xargs printf "%.*f\n" 2)
btc_1h=$(echo $btc | /usr/local/bin/jq ".[0].percent_change_1h" | /usr/bin/xargs printf "%.*f\n" 2)

gnt=$(fetch_data 'golem-network-tokens')
gnt_to_usd=$(echo $gnt | /usr/local/bin/jq ".[0].price_usd" | /usr/bin/xargs printf "%.*f\n" 4)
gnt_24h=$(echo $gnt | /usr/local/bin/jq ".[0].percent_change_24h" | /usr/bin/xargs printf "%.*f\n" 2)
gnt_1h=$(echo $gnt | /usr/local/bin/jq ".[0].percent_change_1h" | /usr/bin/xargs printf "%.*f\n" 2)

xrp=$(fetch_data 'ripple')
xrp_to_usd=$(echo $xrp | /usr/local/bin/jq ".[0].price_usd" | /usr/bin/xargs printf "%.*f\n" 4)
xrp_24h=$(echo $xrp | /usr/local/bin/jq ".[0].percent_change_24h" | /usr/bin/xargs printf "%.*f\n" 2)
xrp_1h=$(echo $xrp | /usr/local/bin/jq ".[0].percent_change_1h" | /usr/bin/xargs printf "%.*f\n" 2)

btc_24h=$(add_arrows $btc_24h)
eth_24h=$(add_arrows $eth_24h)
gnt_24h=$(add_arrows $gnt_24h)
xrp_24h=$(add_arrows $xrp_24h)

btc_1h=$(add_arrows $btc_1h)
eth_1h=$(add_arrows $eth_1h)
gnt_1h=$(add_arrows $gnt_1h)
xrp_1h=$(add_arrows $xrp_1h)

echo "
<html>
  <style>
    * {  margin: 0; padding: 0; }
    body { padding-top: 30px; color: rgba(255, 255, 255, 0.5); font-family: 'Avenir'; font-size: 16px; font-weight: 500; }
    small { font-size: 8px; position: relative; top: -0.5em; }
    div { display: flex; align-items: center; padding: 2px 0 2px 2px; margin: 0 0 2px; border-bottom: 1px solid rgba(255, 255, 255, 0.25); }
    div:last-child { border-bottom: 0; }
    em { font-style: normal; color: rgba(255, 255, 255, 0.9); font-weight: 600; text-shadow: 0 0 2px rgba(0, 0, 0, 0.5); }
    span { width: 14px; text-align: center; margin: 0 10px 0 0; font-size: 14px; }
    strong { font-size: 10px; margin: 0 0 0 8px; opacity: 0.85; }
  </style>
  <body>
"

echo $xrp_to_usd $xrp_1h $xrp_24h | /usr/bin/awk '{print "<div style=\"opacity: 0.5\"><span><img src=\"http://exomel.s3.amazonaws.com/cryptocurrency-ticker/ripple.png\" height=14 /></span> <em>"$1"</em><small>$</small><strong>"$2"</strong><strong>"$3"</strong></div>"}'
echo $gnt_to_usd $gnt_1h $gnt_24h | /usr/bin/awk '{print "<div style=\"opacity: 0.6\"><span><img src=\"http://exomel.s3.amazonaws.com/cryptocurrency-ticker/golem.png\" height=14 /></span> <em>"$1"</em><small>$</small><strong>"$2"</strong><strong>"$3"</strong></div>"}'
echo $btc_to_usd $btc_1h $btc_24h | /usr/bin/awk '{print "<div style=\"opacity: 0.7\"><span><img src=\"http://exomel.s3.amazonaws.com/cryptocurrency-ticker/bitcoin.png\" height=14 /></span> <em>"$1"</em><small>$</small><strong>"$2"</strong><strong>"$3"</strong></div>"}'
echo $eth_to_usd $eth_1h $eth_24h | /usr/bin/awk '{print "<div style=""opacity: 0.8""><span><img src=\"http://exomel.s3.amazonaws.com/cryptocurrency-ticker/ethereum.png\" height=14 /></span> <em>"$1"</em><small>$</small><strong>"$2"</strong><strong>"$3"</strong></div>"}'

echo "
  </body>
</html>
"

exit 0
